### PR TITLE
Create a git submodule for DCSA-Information model

### PR DESCRIPTION
**Pull request by nt-as**
Signed-off-by: Niels Thykier <nt@asseco.dk>

### CODE REVIEW

**Comment by nt-as** [comment]
Migration for existing clones:

```sh
git submodule init
git submodule update
```

From there on, it should be a matter of:

```sh
git pull
```

(modern versions of git updates the submodule automatically on git pull if the submodule is changed)

**Comment by HenrikHL** [comment]
Where do you specify the commit id of InformationModel that the subModule should point to? With this PR it seems to me that it is pointing to master...

**Comment by douradofrazer** [comment]
@nt-as When git action runs, does the submodule refer to master or a specific version? Basically where do we specify this as @HenrikHL asked.

**Comment by nt-as** [comment]
The pointer is shown in github as:

image


This _happens_ to be the commit of the IM master at the time I created this PR, but it will not follow the IM master automatically (this requires a manual commit in the EBL repository)

**Review by HenrikHL — APPROVED** [review]

**Pull request merged**
