### PR TITLE
Allow Booking value pass-through if not specified in POST TD

### PR DESCRIPTION
**Pull request by HenrikHL**
An error should be displayed *only* if set when creating a new TD.
If values on TD are null - no need to check...

### CODE REVIEW

**Comment by HenrikHL** [comment]
ServiceType and ShipmentTerms will be renamed to RecipientDeliveryType and CargoMovementType in a later PR...

**Comment by nt-as** [comment]
I think I am missing context.  The `Objects.equals` method is null-safe.

**Comment by douradofrazer** [comment]
@nt-as is right, or are we missing something ? @HenrikHL

**Comment by HenrikHL** [comment]
Sorry for the confusion. I have changed the title (it was an old title that I forgot to edit...)
The reason for the above code is to avoid duplicating input when creating a TD. So internally we have a POST TD endPoint. The TD requires a lot of fields that are to be copied from Booking. In order to avoid this - it is possible to leave these fields empty (=Null). If this is the case - the value from the Booking is copied into the TD. 
If a value is specified in TD which differs from Booking - an error is returned. It is not allowed to deviate from values already specified at booking.

**Review by nt-as — APPROVED** [review]

**Pull request merged**
